---
- hosts: all
  become: true
  tasks:
    
  - name: Importing users' variables from file
    include_vars:
      file: roles/vars.yml

  - name: Creating primary group
    include_tasks: roles/tasks/sysadmin.yml
      
  - name: Adding local sysadmin users to multiple distro servers
    ansible.builtin.user:
      name: "{{ item.name }}"
      password: "{{ item.password }}"
      comment: "{{ item.comment }}"
      update_password: on_create
      group: sysadmin
      shell: /bin/bash
      state: present
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa
    loop: "{{ users_list }}"
        
  - name: Editing all sudoers files to NOPASSWD for sysadmin group      
    include_tasks: roles/tasks/sudoers.yml

