---
  - name: Importing almalinux playbook 
    import_playbook: almalinux_hosts.yml
  
  - name: Importing SUSE playbook    
    import_playbook: suse_hosts.yml

  - name: Importing Ubuntu playbook
    import_playbook: ubuntu_hosts.yml

# - include_tasks: roles/tasks/homedir.yml
